server:
  port: 18082

# logback 설정
logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    org.springframework.boot.autoconfigure.web: INFO
    com.renzo: DEBUG
    reactor.netty: INFO