version: '3.8'
services:
  presentation-gateway:
    build:
      context: ./presentation-gateway
    ports:
      - "18080:18080"
    networks:
      - app-network

  step-client-server:
    build:
      context: ./step-client-server
    ports:
      - "18081:18081"
    networks:
      - app-network

  step-backend-server:
    build:
      context: ./step-backend-server
    ports:
      - "18082:18082"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"   # Jenkins 웹 인터페이스 포트
      - "50000:50000" # Jenkins 에이전트 통신 포트
    networks:
      - app-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Docker in Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # 초기 설정 생략 (선택 사항)

networks:
  app-network:
    driver: bridge
