server:
  port: 18080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:18081
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment}
        - id: shopping
          uri: http://localhost:18082
          predicates:
            - Path=/shopping/**

      filter:
        rewrite-path:
          enabled: true
